### ISSUE TITLE
 ExtensionInitializationException - `Behat\MinkExtension\Extension` extension file or class could not be located. 

### ISSUE THREAD

**Issue by bizmate** [Behatch/skeleton#2]
Just checked this out. After composer install i tried to run behat but i keep getting this error. 

[Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]  
  `Behat\MinkExtension\Extension` extension file or class could not be located. 

I tried to change some of the versions in composer.json but could not find the right way to make it work.

Not sure where this i configured as it is not a config in behat.yml, should some dependency map to 

Behat\MinkExtension\ServiceContainer\MinkExtension ? https://github.com/Behat/MinkExtension/blob/master/src/Behat/MinkExtension/ServiceContainer/MinkExtension.php 

I ll try to debug it but if you think you have an easy answer pls let me know

**Comment by sanpii** [comment]
Thank you for your report. This is fixed in 6db559a5e6153b2fe737fc6fe656f1686c63d43e.
